### PR TITLE
Various bug fixes and updates for refraction correction, compression, and visualization

### PR DESCRIPTION
**Pull request by binchensun**
- refraction_correction.py: bug fix for CRPIX1 and CRPIX2 updates in save_resample_align(), which used to apply to the second and third axis. Updates for FITS headers and history
- move compression-related functions to utils.py
- add a minimum fraction of frequency channels to fit refraction coefficients. Used to be hard-coded to 5.
- add pixel-size-aware feature in remove_small_objects()
- visualization.py: check REFCOR in the fits header and add a note in the figure title.

### CODE REVIEW

**Review by surajit4444mondal — COMMENTED** [review]
**Compress_fits_to_h5 and reverse function**
For consistency CRPIX1, CRPIX2, CDELT1, CDELT2 should be appropriately changed to take into account this zoom. This would ensure that scientific work can be done using the hdf5 file itself, without needing to convert to fits, if one chooses. The reverse function should use the header information and modify it back.

**Comment by peijin94** [comment]
The h5 file is planned to be transparent for users, the user should not work directly on the compressed array.

Under this mentality, the compression and the recover process is simple full-frame zoom. The zoom ratio should not be modified by user, it has to recover to the original size. This can ensure consistency, that header can be used without any modification, so that recovered fits have exactly the same header and dimension as before compression.

**Review by peijin94 — APPROVED** [review]

**Comment by binchensun** [comment]
Also CRPIX1, CRPIX2, CDELT1, CDELT2 only have one value in a single FITS file. We could somehow make this info into the hdf file, but as @peijin94 said, users probably don't want to interface with the hdf files directly. If desired, we can open an issue in the future and incorporate something. Merge this PR for now.

**Comment by peijin94** [comment]
The complete header is inside the hdf file for the re-compose of the fits file. 
Yes CRPIX CRVAL CDELT only have one single value everywhere in this process.

**Comment by surajit4444mondal** [comment]
> Also CRPIX1, CRPIX2, CDELT1, CDELT2 only have one value in a single FITS file. We could somehow make this info into the hdf file, but as @peijin94 said, users probably don't want to interface with the hdf files directly. If desired, we can open an issue in the future and incorporate something. Merge this PR for now.

That is true actually... So the only way to do this is to have some sort of table in the hdf5 file. And as we discussed last time, we indeed decided that user should always run ovro_lwa_prep/similar to get the fits file and work on that.. So indeed I agree that we can incoporate this, only if there is a request from the user community for such a feature..

**Pull request merged**
